# Generated by Django 6.0.5 on 2026-08-05 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=50)),
                ('bio', models.TextField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('skills_can_teach', models.TextField(blank=True, help_text='Separate skills with commas.')),
                ('skills_want_to_learn', models.TextField(blank=True, help_text='Separate skills with commas.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
